import React, { Component } from 'react';

class Footer extends Component {
  render() {
    return (
		<footer className="site-footer">
            <span className="site-footer-owner"><a href="https://youjinchoi.github.io">youjinchoi.github.io</a> is maintained by <a href="mailto:dev.youjin.choi@gmail.com">Youjin Choi</a>.</span>
            <span className="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
        </footer>
    );
  }
}

export default Footer;
