import React, { Component } from 'react';

class Footer extends Component {
  render() {
    return (
		<footer className="site-footer">
            <span className="site-footer-owner"><a href="https://github.com/pages-themes/cayman">cayman</a> is maintained by <a href="https://github.com/pages-themes">pages-themes</a>.</span>
            <span className="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
        </footer>
    );
  }
}

export default Footer;
